sort_by_menu = "xpath://select[@id='input-sort']"
Default = "Default"
name_AtoZ = "Name (A - Z)"
nameZtoA = "Name (Z - A)"
price_low_to_high = "Price (Low > High)"
price_high_to_low = "Price (High > Low)"
rating_highst = "Rating (Highest)"
rating_lowest = "Rating (Lowest)"
model_AtoZ = "Model (A - Z)"
model_ZtoA = "Model (Z - A)"
